# Generated by Django 5.1.2 on 2024-10-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password2',
            new_name='confirm_password',
        ),
    ]
